pmo_folder="../export/pmo/cat/"
tmh_folder="../export/tmh/cat/"
savefolder="../export/model/cat/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0001" "0002"

pmo_folder="../export/pmo/edit/"
tmh_folder="../export/tmh/edit/"
savefolder="../export/model/edit/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/effect/"
tmh_folder="../export/tmh/effect/"
savefolder="../export/model/effect/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0001" "0002"

pmo_folder="../export/pmo/emmodel/"
tmh_folder="../export/tmh/emmodel/"
savefolder="../export/model/emmodel/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0001" "0002"

pmo_folder="../export/pmo/emmodel/"
tmh_folder="../export/tmh/emmodel/"
savefolder="../export/model/emmodel/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0005" "0006"

pmo_folder="../export/pmo/npc/"
tmh_folder="../export/tmh/npc/"
savefolder="../export/model/npc/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0001" "0002"

pmo_folder="../export/pmo/player/f/arm/"
tmh_folder="../export/tmh/player/f/arm/"
savefolder="../export/model/player/f/arm/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/f/body/"
tmh_folder="../export/tmh/player/f/body/"
savefolder="../export/model/player/f/body/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/f/face/"
tmh_folder="../export/tmh/player/f/face/"
savefolder="../export/model/player/f/face/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/f/hair/"
tmh_folder="../export/tmh/player/f/hair/"
savefolder="../export/model/player/f/hair/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/f/head/"
tmh_folder="../export/tmh/player/f/head/"
savefolder="../export/model/player/f/head/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/f/reg/"
tmh_folder="../export/tmh/player/f/reg/"
savefolder="../export/model/player/f/reg/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/f/wst/"
tmh_folder="../export/tmh/player/f/wst/"
savefolder="../export/model/player/f/wst/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/m/arm/"
tmh_folder="../export/tmh/player/m/arm/"
savefolder="../export/model/player/m/arm/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/m/body/"
tmh_folder="../export/tmh/player/m/body/"
savefolder="../export/model/player/m/body/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/m/face/"
tmh_folder="../export/tmh/player/m/face/"
savefolder="../export/model/player/m/face/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/m/hair/"
tmh_folder="../export/tmh/player/m/hair/"
savefolder="../export/model/player/m/hair/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/m/head/"
tmh_folder="../export/tmh/player/m/head/"
savefolder="../export/model/player/m/head/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/m/reg/"
tmh_folder="../export/tmh/player/m/reg/"
savefolder="../export/model/player/m/reg/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/player/m/wst/"
tmh_folder="../export/tmh/player/m/wst/"
savefolder="../export/model/player/m/wst/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

pmo_folder="../export/pmo/stage/"
tmh_folder="../export/tmh/stage/"
savefolder="../export/model/stage/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0001"

pmo_folder="../export/pmo/stage/"
tmh_folder="../export/tmh/stage/"
savefolder="../export/model/stage/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0002" "0001"

pmo_folder="../export/pmo/weapon/"
tmh_folder="../export/tmh/weapon/"
savefolder="../export/model/weapon/"
echo "Process $pmo_folder & $tmh_folder -> $savefolder"
python3 batch_organize.py "$pmo_folder" "$tmh_folder" "$savefolder" "0000" "0002"

